language: node_js

node_js:
    - 4
    - 5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9

before_install:
    - export CXX=/usr/bin/g++-4.9;
