sudo: true
language: node_js

node_js:
    - 4
    - 5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9

before_install:
    - sudo apt-get install swi-prolog;
    - prolog -v;
    - export SWI_HOME_DIR=/etc/alternatives;
    - export CXX=/usr/bin/g++-4.9;
