sudo: true
language: node_js

node_js:
    - 4
    - 5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9

before_install:
    - sudo apt-get install swi-prolog
    - file /usr/bin/prolog
    - export CXX=/usr/bin/g++-4.9;
    - export SWI_HOME_DIR=/usr/bin
