sudo: true

language: node_js

node_js:
    - 4
    - 5

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    - sudo add-apt-repository ppa:swi-prolog/devel -y;
    - sudo apt-get update;
    - sudo apt-get install swi-prolog g++-5;
    - sudo apt-get install swi-prolog;
    - prolog -v;
    - export SWI_HOME_DIR=/etc/alternatives;
    - export CXX=/usr/bin/g++-4.9;
